### ISSUE TITLE
Mi sono cagato addosso

### ISSUE THREAD

**Issue by AnubiSgravato** [Alessandro707/PublicPettoMate#2]
ho fatto tanta cacca molle nelle mutande. Odore acre, colore giallognolo.
Procedo con lo sburare, per creare la cacasbura
ciao 🤣😂🤣🤣😋😙😉🤩

**Comment by Alessandro707** [comment]
Grazie per la segnalazione, seguo a risolvere il problema da lei segnalato. 🎶🤞😊🤦‍♂️💋🤦‍♀️🐱‍👤

BaehSoftware®
